ebachannel_admin_category_homepage:
    path:     /hello/{name}
    defaults: { _controller: EbachannelAdminCategoryBundle:Default:index }
admin_categorys:
    resource: "@EbachannelAdminCategoryBundle/Resources/config/routing/routing.yml"
    prefix:   /admin/category