admin_category_index:
    path:   /index
    defaults: { _controller: "EbachannelAdminCategoryBundle:Default:index" }
admin_category_new:
    path:     /new
    defaults: { _controller: "EbachannelAdminCategoryBundle:Default:new" }
admin_category_edit:
    path:     /edit/{id}
    defaults: { _controller: "EbachannelAdminCategoryBundle:Default:edit" }
admin_category_update:
    path:     /update/{id}
    defaults: { _controller: "EbachannelAdminCategoryBundle:Default:update" }
    requirements: { _method: post|put }
admin_category_delete:
    path:     /delete/{id}
    defaults: { _controller: "EbachannelAdminCategoryBundle:Default:delete" }