front_thread_index:
    path:   /index/{category_id}
    defaults: { _controller: "EbachannelFrontThreadBundle:Default:index" }
front_thread_new:
    path:   /new/{category_id}
    defaults: { _controller: "EbachannelFrontThreadBundle:Default:new" }