ebachannel_front_response:
    resource: "@EbachannelFrontResponseBundle/Resources/config/routing.yml"
    prefix:   /

ebachannel_front_category:
    resource: "@EbachannelFrontCategoryBundle/Resources/config/routing.yml"
    prefix:   /

ebachannel_front_thread:
    resource: "@EbachannelFrontThreadBundle/Resources/config/routing.yml"
    prefix:   /

ebachannel_admin_category:
    resource: "@EbachannelAdminCategoryBundle/Resources/config/routing.yml"
    prefix:   /


win_road_hello:
    resource: "@WinRoadHelloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
