category_list:
    resource: "@CategoryListBundle/Resources/config/routing.yml"
    prefix:   /

win_road_hello:
    resource: "@WinRoadHelloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
