admin_category_post:
    resource: "@AdminCategoryBundle/Resources/config/routing/post.yml"
    prefix:   /post

admin_category_homepage:
    path:     /admin/category/{page}
    defaults: { _controller: AdminCategoryBundle:Default:index }
