ebachannel_front_thread_homepage:
    path:     /front/thread/{name}
    defaults: { _controller: EbachannelFrontThreadBundle:Default:index }

ebachannel_front_thread:
    resource: "@EbachannelFrontThreadBundle/Resources/config/routing/routing.yml"
    prefix:   /front/thread