product:
    path:   /
    defaults: { _controller: "AdminCategoryBundle:Default:index" }
product_new:
    path:     /new
    defaults: { _controller: "AdminCategoryBundle:Default:new" }
product_edit:
    path:     /edit
    defaults: { _controller: "AdminCategoryBundle:Default:update" }
