product:
    path:   /listShow
    defaults: { _controller: "AdminCategoryBundle:Default:index" }
product_new:
    path:     /new
    defaults: { _controller: "AdminCategoryBundle:Default:new" }
product_edit:
    path:     /{id}/detailEdit
    defaults: { _controller: "AdminCategoryBundle:Default:edit" }
product_delete:
    path:     /{id}/detailDelete
    defaults: { _controller: "AdminCategoryBundle:Default:delete" }
