product_index:
    path:   /index
    defaults: { _controller: "AdminCategoryBundle:Default:index" }
product_detail:
    path:   /detail
    defaults: { _controller: "AdminCategoryBundle:Default:detail" }
product_new:
    path:     /new
    defaults: { _controller: "AdminCategoryBundle:Default:new" }
productBulkNew:
    path:     /bulkNew
    defaults: { _controller: "AdminCategoryBundle:Default:bulkNew" }
product_edit:
    path:     /edit/{id}
    defaults: { _controller: "AdminCategoryBundle:Default:edit" }
product_update:
    path:     /update/{id}
    defaults: { _controller: "AdminCategoryBundle:Default:update" }
    requirements: { _method: post|put }
product_delete:
    path:     /delete/{id}
    defaults: { _controller: "AdminCategoryBundle:Default:delete" }

