Ebachannel\Admin\CategoryBundle\Entity\category:
    type: entity
    table: category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: text
    lifecycleCallbacks: {  }
