Ebachannel\Admin\CategoryBundle\Entity\response:
    type: entity
    table: response
    id:
        'no':
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
        threadId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: thread_id
    fields:
        userName:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: user_name
        userMail:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
            column: user_mail
        body:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        deleteFlag:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: delete_flag
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
    lifecycleCallbacks: {  }
