Ebachannel\Admin\CategoryBundle\Entity\thread:
    type: entity
    table: thread
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        category_id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: category_id
        updated_at:
            type: datetime
            nullable: false
            comment: ''
            column: updated_at
        body:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''

    lifecycleCallbacks:
        prePersist: [ prePersist ]
    