Ebachannel\Admin\CategoryBundle\Entity\category:
    actAs: { Timestampable: ~ }
    type: entity
    table: thread
    id:
        id:
            type: integer
            primary: true
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: text
        category_id:
            type: integer
        last_update_time:
            type: datetime            
    lifecycleCallbacks: {  }
